- src/ttblit/asset/image.py
Currently `load_from_packed` is reading past the end of the buffer. (Noticed as I use `-fsanitize=address` on local debug builds.)
Also, should sprites default to packed? I just spent a while debugging `load_from_packed`, then realised I was trying to load a raw sprite...
> Payload size is just the image data size

- README.md
- src/README.md
- src/tests/test_image_cli.py
- src/ttblit/asset/image.py
This set of changes removes the `packed` flag, which should be the default behaviour, and replaces it with a `raw` flag which, when supplied, causes the image packing tool to output raw RGB or RGBA values with no header. Raw image data can be used to initalise a surface and should not be loaded with `SpriteSheet::load`.
> Support raw, headerless image output

- src/tests/test_image_cli.py
- src/tests/test_metadata.py
- src/tests/test_setup.py
- src/ttblit/__init__.py
- src/ttblit/asset/font.py
- src/ttblit/asset/map.py
- src/ttblit/tool/metadata.py
Allows title, description, version, icon and splash to be packed and prepended to a 32blit .bin file.
icon should be an 8x8 .png
splash should be a 128x96 .png
Images can be configured just like the asset pipeline- packed, unpacked, paletted, etc
Example metadata.yml:
```yml
title: Rocks & Diamonds
description: A game of rocks and diamonds
version: v1.0.0
icon:
file: icon-8x8.png
splash:
file: splash-128x96.png
```
> Add metadata packing tool

- src/tests/test_packer_cli.py
- src/ttblit/tool/packer.py
Adds a test for the packer with paths relative to the working directory, and fixes it by catching the "palette" option and prefixing it with the working directory if it is not an absolute path.
This is one to expand in future, since there may be other filename/path option supplied to future asset builders that could fail in the same way.
Should fix #15!
> Prefix palette with working dir for #15

- src/ttblit/tool/flasher.py
Corresponding change to the subfolder indexing in https://github.com/pimoroni/32blit-beta/pull/370 - allows games to optionally be saved into subdirectories.
> Add directory support to flash save

- src/tests/test_metadata.py
- src/ttblit/tool/metadata.py
This tweak adds "author" to the metadata.
It also prefixes each text field with a single char, denoting the field type.
I don't know if this is the best way to accomplish future expansion or additional metadata that 32blit could ignore... but at least it opens the discussion to how we deal with new text fields.
Maybe the core metadata should be more rigidly defined to make parsing cleaner/simpler - ie fixed-length fields that can be slurped into a predefined struct.
Any *extra* data could then be appended onto the end.
Nice to haves would be additional fields such as author URL and long description that are ignored by 32blit, but carried around with the .bin for display in game manager tools or web front ends.
> Add author field, prefix metadata fields

- src/tests/test_packer_cli.py
- src/ttblit/__init__.py
- src/ttblit/asset/font.py
- src/ttblit/asset/image.py
- src/ttblit/core/assetbuilder.py
- src/ttblit/core/palette.py
- src/ttblit/core/tool.py
- src/ttblit/tool/cmake.py
- src/ttblit/tool/flasher.py
- src/ttblit/tool/metadata.py
- src/ttblit/tool/packer.py
This PR does two things:
1. Redirects error output to `stderr`
2. Re-route all `stdout` output through `logging` with new `-v` command to permit info and debug messages.
Should fix #8
> Make 32blit tools less noisy, fixes #8

- src/ttblit/tool/cmake.py
This is a bit of a rough and ready fix for #22 since it currently only supports the "palette" argument and doesn't parse the .yml config in enough detail to determine what kind of input data it should be looking for.
This may need to guess the input file type so that it can iterate through the `AssetBuilder.options` and detect `Path` and `Palette` types, but right now it works because - afaict - "palette" is the only additional file requirement used by any of the asset builders.
> Allow cmake tool to detect dependent files in arguments

- src/tests/test_cmake.py
- src/ttblit/tool/cmake.py
Should fix pimoroni/32blit-beta#387
> Empty cmake file when no metadata inputs

- src/tests/test_cmake.py
- src/ttblit/tool/cmake.py
Copies the crude asset packer code that rewrites a single string option into a dict. It works!
> Add test for and fix #28

- src/tests/test_cmake.py
- src/ttblit/tool/cmake.py
Also removed the special case for no-inputs as an empty but set variable is valid and it was the easiest thing to do.
> Include variables for metadata fields in the CMake file

- src/tests/test_packer_cli.py
- src/tox.ini
- src/ttblit/__init__.py
- src/ttblit/asset/font.py
- src/ttblit/asset/image.py
- src/ttblit/core/assetbuilder.py
- src/ttblit/core/tool.py
- src/ttblit/tool/packer.py
Previously a call to the `register_asset_builders` function was required when using the asset packer to register all the asset tools with the packer, these were then passed into an `AssetSource` instance where they were used to handle the build process of a single asset by "guessing" the appropriate tool.
Rather than faff around passing these from `__init__` all the way down to where they're used, this change defines the builders inside the `AssetSource` class. An instance is only created for a specific builder if it's used during a source `build`.
To make this change possible I've elminated the need to pass in a `parser` argument to `Tools`. IIRC the parser - which is used to set up `argparse` for handling tool arguments - is not used at all when invoking tools via the `AssetBuilder`. …
> Use fresh class instances for each packed asset

- src/tests/test_metadata.py
- src/ttblit/tool/metadata.py
This replaces #38 and kicks the tests so the extra argument check is triggered.
> Require either --config or --file

- src/ttblit/tool/metadata.py
This applies to icns generation and metadata compiling, and allows the metadata `--config` argument to specify a file not in the current working directory.
> Find images when not in working dir

- src/ttblit/tool/flasher.py
This fixes an apparent issue where - and I'm assuming here from observing the behaviour, not the actual serial data - the RST command was getting appended to the beginning of the subsequent command and causing the device to reset with an open serial connection. This shunts the device mid-flash from `ttyACM0` to `ttyAMC1` on my system and causes the flash operation to stall predictably at 3904 bytes.
This only happens when a reset is required from game to firmware state for flashing.
This might also fix the ol' stuck-the-end bug, too.
This PR also flushes after each chunk for good measure.
> Ensure RST is flushed to device before closing

- src/ttblit/__init__.py
A slight rewrite of how shorthand commands are handled to avoid accidentally creating any special cases we need to worry about.
Now just rewrites `sys.argv` and lets it drop to the regular command processing. Effectively acting as an alias.
> Support `32blit flash filename.blit`

- src/ttblit/__init__.py
It did the same thing as `32blit flash thing.blit` instead of saving to SD (like it used to do)
> Fix 32blit thing.blit

- src/tests/test_packer_cli.py
- src/tests/test_packer_cli/assets_multi_out.yml
- src/ttblit/tool/packer.py
This is so that you can do
```yaml
assets/Comic_Sans_MS.ttf:
- name: comic_font_12
height: 12
- name: comic_font_14
height: 14
```
For the fun edge case that is fonts. Test maybe coming soon. (Definitely not just opening this PR so that the tests will run...)
> Handle one asset to multiple outputs with different options

- src/ttblit/tool/flasher.py
Allows using the flasher tool through WSL with `--port /dev/ttySx`.
> Allow a user specified port with no VID/PID info

- src/ttblit/tool/cmake.py
Missed in #52. Guess this should be tested by passing the same config as the packer test...
> Handle multiple sets of options in the CMake tool

- src/tests/test_map.py
- src/ttblit/asset/builders/map.py
- src/ttblit/asset/builders/raw.py
Adds new options for "map" types- currently we only support "tmx" so I wonder if "AssetMap" and "map" should globally be "tmx" and future map formats should have their own class.
New options:
1. `--empty-tile` or `empty_tile` - specifies the tile which 0-indexed (empty) tiles will be remapped to. Defaults to 0. All other tile indexes are offset by -1 to give 0-based tile indexes into our spritesheets so `0` has to go *somewhere*
2. `--output-struct` or `output_struct` - the asset builder will output a struct with some basic map info, instead of just a raw binary of the layers.
The struct looks like:
```
"MTMX"  - 4 bytes, utf8 encoded
width - 2 bytes unsigned uint16_t
height - 2 bytes unsigned uint16_t
layers - 2 bytes unsigned uint16_t
data - width * height * layers bytes (uint8_t) of …
```
> Remap and struct options for tmx maps

- src/setup.cfg
If click is not fixed to a minimum version number it has the potential to crash the 32blit tool when executed resulting in a broken build of a 32blit game.
> Set minimum version number of dependency

- src/ttblit/__init__.py
- src/ttblit/core/blitserial.py
- src/ttblit/tool/flasher.py
This goes with https://github.com/32blit/32blit-sdk/pull/605 to finish making launching after flash optional. It also allows launching after saving a file to the SD card.
> Add a launch command and a --launch flag to install

- src/tests/test_map.py
- src/ttblit/asset/builders/map.py
Per discussion in Discord this PR replaces #74 with some tweaks to canonicalise on `struct.pack` for both 8bit and 16bit tile formats. The data produced is `uint8_t` in both cases, but data for 16bit tiles will be twice the size and require a slightly different `TMX` struct to work with:
```c++
struct TMX16 {
char head[4];
uint8_t empty_tile;
uint16_t width;
uint16_t height;
uint16_t layers;
uint16_t data[];
};
```
> Support for 16bit tmx tile indexes, replaces #74

- .github/workflows/test-setup.yml
- src/tests/test_setup.py
- src/ttblit/__init__.py
- src/ttblit/tool/setup.py
Helps setting up a new project/ getting the SDK. Probably needs more error handling and tests,
> WIP Setup tool

- src/ttblit/asset/builders/map.py
Tiled stores transforms in the highest 3 bits of the tile index:
- (1 << 31) = H Flip
- (1 << 30) = V Flip
- (1 << 29) = X/Y Swap
Shifted down, this matches what TileMap/Map expect. This is different to SpriteTransform though... (H flip and swap x/y are the other way around...)
I'm just appending the transform data after the tiles, maybe this should be optional to not make maps twice the size if you're not using them?
(Layer 0 tiles, layer 1 tiles, ... layer 0 transforms, layer 1 transforms)
> Handle tiled transforms

- src/tests/test_dfu_cli.py
- src/tests/test_setup.py
- src/tox.ini
- src/ttblit/__init__.py
- src/ttblit/asset/builders/map.py
- src/ttblit/core/dfu.py
- src/ttblit/tool/dfu.py
- src/ttblit/tool/setup.py
Finally addresses #49 and brings the DFU tool under the 32blit tools umbrella where it - hopefully - wont be so neglected.
This is really only a utility for packing the output .bin files into a DFU-compatible file and is mostly only useful for Windows folks using DFuSe Demo to perform a firmware upgrade.
Could be useful for alt firmware dev and other stuff though...
> Add the DFU tool

- src/ttblit/core/blitserial.py
Add the filename after "Flashing" so that it's clear what file is being processed if you, for example, run:
`for f in examples/*/*.blit; do 32blit install $f; done`
Rename the input stream "file" to "input_file" so it doesn't shadow the "file" Pathlib in the outer scope.
(Mentioned in #84)
> Add filename to flasher output

- src/ttblit/asset/formatters/c.py
Causes `TextWrapper.fill` to use a simpler regex, speeding up big arrays a bit.
Minor change found while messing around with build profiling... (voxel/mp3 were taking a while to handle assets). Could probably be reworked further to not join, then immediately re-split in textwrap... but I'm already getting distracted :laughing: .
Makes a clean debug build of the voxel example ~1 second faster (from a ~18s single-threaded build)
> Set break_on_hyphens=False to optimise C output

- src/tests/test_metadata.py
- src/ttblit/core/struct.py
- src/ttblit/tool/metadata.py
Tool for https://github.com/32blit/32blit-sdk/pull/770. (Well, an alternative output for the metadata tool)
> Pico metadata/binary info tool

- src/tests/test_metadata.py
- src/ttblit/tool/metadata.py
This was the tools part of https://github.com/32blit/32blit-sdk/pull/686, which I apparently forgot about.
> Standalone metadata output

- .github/workflows/test.yml
- src/tox.ini
Apparently `py.test` is no longer a supported way of referring to the pytest module.
> Use pytest instead of py.test, and test more Python versions

- src/tests/test_blitserial.py
- src/ttblit/core/blitserial.py
The terminating null should be sent after the offset. Sending it before causes the offset to be 256x too big, because it is little endian.
Also adds a log message, not shown by default.
> Fix bug when deleting from flash and add unit tests
